server.port: 9090



spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/hello_gifty?directConnection=true&serverSelectionTimeoutMS=2000&appName=mongosh+1.6.0

  redis:
    host: localhost
    port: 6379


  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
